branches:
  - name: main
  - name: semantic-release # TODO: remove this
    prerelease: next
    channel: next
  # - name: next
  #   prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - [
      '@semantic-release/release-notes-generator',
      { 'writerOpts': { 'commitsSort': ['subject', 'scope'], 'headerPartial': "## What's Changed" } },
    ]
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - [
      '@semantic-release/git',
      { message: "build(release): 🚀 v${nextRelease.version} 🦉\n\n${nextRelease.notes}\n[skip ci]" },
    ]
# dryRun: true # TODO: remove this
