branches: [main, next]
plugins:
  - '@semantic-release/commit-analyzer'
  - ['@semantic-release/release-notes-generator', { 'writerOpts': { 'commitsSort': ['subject', 'scope'] } }]
  - '@semantic-release/changelog'
  - [
      '@semantic-release/git',
      {
        # TODO: once docker builds are a thing, we're going to have to manually add the assets
        # since we're also updating the action.yml file with every release!
        # Uncomment this line below once those changes are live:
        # assets: ['action.yml', 'CHANGELOG.md', 'package.json', 'package-lock.json'],
        message: "build(release): 🚀 v${nextRelease.version} 🦉\n\n${nextRelease.notes}\n[skip release ci]",
      },
    ]
  # `npm` must be after `git` because we need the `prepare`step of the `git` plugin
  # to execute first so it can create the build commit since we do some add'l tagging
  # in the `postversion` npm hook
  - '@semantic-release/npm'
  # Lightweight alternative to `@semantic-release/github` that creates a draft release
  - ['@semantic-release/exec', { 'publishCmd': 'gh release create ${nextRelease.version} --draft --generate-notes' }]
